// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by ModAssemblyInfo.csproj.
// Make any needed changes in ModAssemblyInfo.csproj.

namespace IBLIV
{
    /// <summary>
    /// Make assembly info available as constant strings.
    /// </summary>
    public class ModAssemblyInfo
    {
        public const string Name        = "IBLIV";
        public const string Version     = "1.0.6";
        public const string Title       = "Improved Building Level Info View";
        public const string Description = "Improvements to the Building Level info view.";
    }
}
